name = "animemaster-bangumi-auth"
main = "worker.js"
compatibility_date = "2026-04-16"
workers_dev = true
preview_urls = true
routes = [
  { pattern = "auth.congutsun.com", custom_domain = true }
]

[[kv_namespaces]]
binding = "BANGUMI_AUTH_KV"
id = "cde856e4cf7e4af28d946732ee4342af"

[triggers]
crons = [ "0 */6 * * *" ]

# Required secrets:
# wrangler secret put BANGUMI_CLIENT_ID
# wrangler secret put BANGUMI_CLIENT_SECRET
# wrangler secret put BANGUMI_CALLBACK_URL
